### ISSUE TITLE
[ASK] Is this a missplaced or not ?

### ISSUE THREAD

**Issue by zhoeryamh** [MadeBaruna/paimon-moe#1]
I found this at Wish Counter, while counting my wish history using auto import.
![image](https://user-images.githubusercontent.com/46564676/110415703-e9d61980-80c4-11eb-809c-5fe05f9120fc.png)

is the calculation misplaced ?. i don't think (296 / 90) is 54 tho.

But this is a nice tool for regreting my life. *thumbs up

**Comment by MadeBaruna** [comment]
Ah the 5* counter is to count your current 5* pity. On your screenshot means you have pull 54 times after your last 5* drop

**Comment by zhoeryamh** [comment]
Oh, so that's the function (damn i don't know I'm dis dum).
It's great if you add some description or like "54 pull left until 5* Guaranteed" or something like that.

Ngl it's a nice tool.
Thanks for the answer.

**Comment by MadeBaruna** [comment]
Thanks for the feedback! Will add some tooltip for that
