### ISSUE TITLE
Unable to Lower Character Constellation Below C7 if Imported Wishes

### ISSUE THREAD

**Issue by DevJinnial** [MadeBaruna/paimon-moe#100]
So if you import your wishes but have gotten more than 6 duplicates, the counter will set it to be above C6 and can not be lowered below the amount you received from wishing

**Comment by roysoetantio** [comment]
I dont mind not to be able to lower passed what the "auto import" data has captured, but maybe have a toggle to view all the characters that has C above C6 to appeared as C6 instead. Showing C7 and above just doesnt make sense (i mean visually) - but some people would love this feature, so view toggle would be nice :D
