### ISSUE TITLE
Any plan for Japanese translation?

### ISSUE THREAD

**Issue by shawnrivers** [MadeBaruna/paimon-moe#103]
Thank you so much for creating such a great tool!
I think the Genshin Impact travelers in Japan are going to love this tool!

Do you guys have any plan of adding Japanese translation?
If there is no plan yet, maybe I help make a PR for the Japanese translation (but not any soon I'm sorry).

**Comment by MadeBaruna** [comment]
I will accept any translation PR (if the game support it)
