### ISSUE TITLE
Wish counter for Ayaka's banner doesn't show

### ISSUE THREAD

**Issue by rushkii** [MadeBaruna/paimon-moe#106]
When you release wish counter for Ayaka's banner? I've been pulling for Ayaka but the web paimon.moe doesn't counting my pity, the latest banner is still Kazuha.

**Comment by MadeBaruna** [comment]
its already updated for the ayaka banner, make sure to wait about 1 hour after wishing before importing

**Comment by MadeBaruna** [comment]
closed for now, please reopen if you have more information
