### ISSUE TITLE
New Talent Level-Up Material not showing up in "farmeable today"

### ISSUE THREAD

**Issue by DenisLogvin** [MadeBaruna/paimon-moe#112]
When I add Ayaka to my TODO list the Teachings/Guide to Elegance don't show up in the summary part as "Farmable Today"

EDIT: It's Wednesday today (Elegance is farmed on Tuesdays.) It looks like the date for when you can farm the elegance guides is wrong - it's Wednesday instead of Tuesday.

**Comment by kyraex** [comment]
I can confirm that the farmeable today material are inaccurate for Elegance (It should be Light instead).
Monday/Thursday : Transience
Tuesday/Friday: Elegance
Wednesday/Saturday: Light
