### ISSUE TITLE
Wish History

### ISSUE THREAD

**Issue by githubforzack** [MadeBaruna/paimon-moe#121]
It hasn't been updating my wish history for Ayakas banner, it says I only have 76 wishes which ends at kazuha while I actually have double that and have been wishing on ayaka.

**Comment by MadeBaruna** [comment]
have you reimport again?

**Comment by mmn6d6d6e** [comment]
the website read whatever appears on your `Paimon Menu > Wish > History` every time you do `Auto Import`.

make sure it's already updated before do the Auto Import. if it isn't updated yet, please wait at least one hour like what was mentioned there.

**Comment by githubforzack** [comment]
i reimported and it worked thanks
