### ISSUE TITLE
Character Page Has The Wrong Constellations 

### ISSUE THREAD

**Issue by Canoeven** [MadeBaruna/paimon-moe#125]
When I go to the character page there are quite a few characters with the incorrect listed constellation amounts, some of them show C1 when the character is C4 for example.

**Comment by MadeBaruna** [comment]
The constellation count is from the wish history.
So if you have missing wishes (maybe its from 6 months ago, and you just import the wish history), the data will not be accurate.
And can't really know constellation bought from paimon shop or from event. You can edit it manually tho.
