### ISSUE TITLE
Characters Constellation

### ISSUE THREAD

**Issue by Spimy** [MadeBaruna/paimon-moe#130]
Before I have imported my wishes from Genshin, I have manually set the constellations of characters that I own in the characters page. However, now that I've imported my wishes, it seems that the number of times I got that character was also taken into account and added to the constellations of my characters. I do not want that as it does not seem to be very accurate? For example by Yanfei is at C12, Diona is at C7 and Chongyun is at C8 as shown in the picture below. I tried to lower it to C6 manually but it blocks me from doing so and cannot go any lower.

![image](https://user-images.githubusercontent.com/34989646/130439305-08847fd0-9bc6-4f76-87a0-01d06e8e6725.png)

Suggestions:
- [ ] Remove limit on the amount of time I can press the "minus" button for constellations (until it is at C0)
- [ ] When importing wishes, add a checkbox to confirm importing character constellations into the characters page

**Comment by roysoetantio** [comment]
or maybe just add toggle to view character above C6 to appear as C6? i think that would make it much easier and/or faster to code.
