### ISSUE TITLE
Traveler Calculator (Talent)

### ISSUE THREAD

**Issue by HiranoKohta** [MadeBaruna/paimon-moe#131]
![Traveler Anemo](https://www.upload.ee/image/13420161/Calculator_-_Paimon.moe.png)
![Travelet Geo](https://www.upload.ee/image/13420163/Calculator_-_Paimon.moe__1_.png)
![Traveler Electro](https://www.upload.ee/image/13420163/Calculator_-_Paimon.moe__1_.png)

**Comment by MadeBaruna** [comment]
Fixed
