### ISSUE TITLE
Format json data files

### ISSUE THREAD

**Issue by mrfuggy** [MadeBaruna/paimon-moe#137]
Format json files in data directories for human readable representation. Don't make the whole file on one line.
```
src/data/achievement
src/data/artifacts
src/data/furnishing
src/data/weapons
```

Advantages:
- Make the file view of the list of achievements or weapons human readable without additional formatting.
- This will improve diff viewing. For example, it is easier to find achievements added after a specific version.
- Makes it easier to add new items.

If you agree with these statements, I can prepare a PR for this.

**Comment by MadeBaruna** [comment]
These file is auto generated and not meant to be edited manually
