### ISSUE TITLE
Error code returned from MHY api

### ISSUE THREAD

**Issue by jos9260** [MadeBaruna/paimon-moe#146]
![Screenshot_20210913-184018_Chrome](https://user-images.githubusercontent.com/74687224/133037064-628e6107-3205-4d33-b782-4130d6cbd010.jpg)

Ive followed all the instructions and even looked in the FAQ but still does not load my data what do i do? im on ps4

**Comment by MadeBaruna** [comment]
PS4 QR Code has changed, the only way I know for now is link your ps account to mihoyo account and use PC/mobile

**Comment by jos9260** [comment]
Ok thanks for the quick reply.
