### ISSUE TITLE
Cannot clone?

### ISSUE THREAD

**Issue by MomokkoW** [MadeBaruna/paimon-moe#15]
It seems that there's a \n in some of the file names
![image](https://user-images.githubusercontent.com/78632509/111573362-58ae2380-87e5-11eb-8550-e0e2cd51ef0e.png)
![image](https://user-images.githubusercontent.com/78632509/111573583-c35f5f00-87e5-11eb-95a0-dfd234a74dbf.png)

**Comment by MadeBaruna** [comment]
Will fix it ASAP
