### ISSUE TITLE
Migrate to SvelteKit

### ISSUE THREAD

**Issue by benmccann** [MadeBaruna/paimon-moe#158]
Sapper is no longer actively developed and SvelteKit is a much better experience

Migration guide: https://kit.svelte.dev/migrating

**Comment by MadeBaruna** [comment]
Hello, thanks for the heads up. I'm been trying to migrate to SvelteKit but I got some issue related to some functions executed twice  (maybe related to https://github.com/sveltejs/kit/issues/1214 or https://github.com/sveltejs/kit/issues/2130 or https://github.com/sveltejs/kit/issues/2527) and got overwhelmed by it, maybe I will take a look again later

**Comment by benmccann** [comment]
@MadeBaruna do you have a branch with your progress thus far that you can share? I'd be happy to take a look

(I'm the primary maintainer of SvelteKit at the moment and was looking for some bigger sites on Sapper to make sure that everyone is able to migrate and we're aware of all issues before we declare 1.0)
