### ISSUE TITLE
Owned and unowned C0 characters indistinguishable on the list-view of the Characters section

### ISSUE THREAD

**Issue by 5310** [MadeBaruna/paimon-moe#162]
The Characters section visibly dims out unowned characters in the grid-view. However, no such dimming, or any other markings are shown for unowned characters in the list view of the Characters section.

Example below where I don't own Qiqi or Hu Tao, but do own Albedo, all of which are indistinguishable in the list-view:
![Screenshot_20211016_124642](https://user-images.githubusercontent.com/112914/137578031-48aa25fa-7133-4a6a-9547-489598201ac4.png)
![Screenshot_20211016_124649](https://user-images.githubusercontent.com/112914/137578037-34e1fb0b-96e1-40f6-bd75-94c1f5086667.png)

The list-view does however show constellations for owned characters correctly, so I suspect this is a bug.

Additionally worth noting: Clicking on the character entries on the list-view does not open their pages like it does on the grid-view, which is a bit unexpected.

**Comment by MadeBaruna** [comment]
I see what you mean, will check later
