### ISSUE TITLE
Error Resin Calculation

### ISSUE THREAD

**Issue by dotslashf** [MadeBaruna/paimon-moe#17]
If user setting AR and WL in setting section with number greater than the actual current max AR and WL (60 for AR and 8 for WL) resin calculation in to do error 
![Screenshot from 2021-03-21 20 15 47](https://user-images.githubusercontent.com/38921923/111904678-b018f180-8a7a-11eb-98c0-3e446abb7726.png)
![Screenshot from 2021-03-21 20 15 20](https://user-images.githubusercontent.com/38921923/111904679-b0b18800-8a7a-11eb-8777-fa5781c08203.png)
After setting to 1000 AR and 1000 WL
![Screenshot from 2021-03-21 20 16 21](https://user-images.githubusercontent.com/38921923/111904674-ae4f2e00-8a7a-11eb-8f69-78c1077bdc19.png)
![Screenshot from 2021-03-21 20 16 07](https://user-images.githubusercontent.com/38921923/111904677-af805b00-8a7a-11eb-897f-8bfc33c01fac.png)

**Comment by fadhluu** [comment]
Actually i have already solving it with adding Max AR and WL, later i'll add PR after you review https://github.com/MadeBaruna/paimon-moe/pull/16
