### ISSUE TITLE
takagg import issue

### ISSUE THREAD

**Issue by jungco7** [MadeBaruna/paimon-moe#181]
I changed all Korean reward names to English, but still does not proceed in "Processing..."
[this file](https://docs.google.com/spreadsheets/d/1n7RlChglv4JDHFvh7RO4lEMDsTk071zf/edit?usp=sharing&ouid=114153347278772394178&rtpof=true&sd=true)
Anything more to fix here?

**Comment by MadeBaruna** [comment]
You need to change the sheet name

**Comment by jungco7** [comment]
> You need to change the sheet name

It was the same result when I changed the sheet name to '1' '2' '3' '4'
[this file](https://docs.google.com/spreadsheets/d/1wXu_MEld0GITY1poN20lZoMtuw1oZFJN/edit?usp=sharing&ouid=114153347278772394178&rtpof=true&sd=true)
tell me what name i should change

**Comment by MadeBaruna** [comment]
Character Event Wish
Weapon Event Wish
Permanent Wish
Novice Wishes

**Comment by jungco7** [comment]
> Character Event Wish Weapon Event Wish Permanent Wish Novice Wishes

works well thanks
