### ISSUE TITLE
Problems about "travellers"

### ISSUE THREAD

**Issue by MomokkoW** [MadeBaruna/paimon-moe#19]
```
  traveler_anemo: {
    name: 'Traveler (Anemo)',
    id: 'traveler_anemo',
    rarity: 5,
    element: elements.anemo,
    weapon: weapons.sword,
    sex: "player's choice",
```

```
  traveler_geo: {
    name: 'Traveler (Geo)',
    id: 'traveler_geo',
    rarity: 5,
    element: elements.geo,
    weapon: weapons.sword,
    sex: "player's choice",
```
But it's seems that you mean Geo=Aether(Kong) and Anemo=Lumine(Ying)?(by their head porttaits on the website)
And they're not from Mondstadt exactly (I don't know why fandom English wiki says that,but fandom Traditional Chinese wiki puts it in the "other",so does the Simplified Chinese wiki.)

**Comment by MadeBaruna** [comment]
No, I use that because of the talent difference. And why the pictures are not the same, only because I want it to be different :)

**Comment by MomokkoW** [comment]
Though,to my intuition,I think Geo=Aether and Anemo=Lumine too XD

**Comment by MomokkoW** [comment]
And what about their nation?Shouldn't be Mondstadt(I still think fandom English wiki is wrong)

**Comment by MadeBaruna** [comment]
Yeah maybe the nation is wrong, but its not used for now

**Comment by MomokkoW** [comment]
👌
