### ISSUE TITLE
Wish counter auto import connection timeout

### ISSUE THREAD

**Issue by Arhorn** [MadeBaruna/paimon-moe#190]
When i tried reimport wishes:
![image](https://user-images.githubusercontent.com/29491919/143177209-386ee19b-0a37-488e-ba1f-403aa7d6e791.png)

**Comment by teufik2305** [comment]
I think it has to do something with new event banners Character Event Wish-2 it used to be Character Event Wish.

**Comment by LokeYourLord** [comment]
Same issue, just wanted add a +1
