### ISSUE TITLE
Owned Characters not displaying.

### ISSUE THREAD

**Issue by TheGenshinPlayer** [MadeBaruna/paimon-moe#194]

**Comment by TheGenshinPlayer** [comment]
I have done what the instructions say, but it still doesn't show all the characters I got. It only shows the starters and the most recent ones. Same with wishes. Is that normal?

**Comment by npanuhin** [comment]
Wish Counter only imports your latest pulls, so any pulls more than 6 months old will not be imported. Missing characters can be entered manually on the Characters page. Does this solve your problem, or are you talking about not-so-old pulls?
