### ISSUE TITLE
bug or not 

### ISSUE THREAD

**Issue by willay11** [MadeBaruna/paimon-moe#2]
look like the last auto import still in here while im import new data ( new ID ) since my id(new import) dont have the chara/weapon as i know it from my other id , the current import have diluc ganyu on chara banner but not count , maybe you can add refresh/reset tool for wish counter , anyway this is good tool and simply easy to use thx . 
![image](https://user-images.githubusercontent.com/80321959/110454532-edd05e80-80f9-11eb-84a6-426794f9ff41.png)

**Comment by MadeBaruna** [comment]
Yeah for now only supporting 1 account, subsequent import will append the history, so you can keep the history more than 6 months. I will add support for multiple account to my todo list

**Comment by MadeBaruna** [comment]
Will be fixed when #3 finished

**Comment by MadeBaruna** [comment]
Multiple account was implemented, please check it on setting :)
