### ISSUE TITLE
talent Material  - traveler geo

### ISSUE THREAD

**Issue by Dyakey** [MadeBaruna/paimon-moe#206]
I think that talent material for traveler geo is wrong. It should be 'Philosophies of Gold' instead of 'Teachings of Prosperity'. :>

**Comment by HansonSin** [comment]
Hmm, I think it has both.

![IMG_20220104_005450](https://user-images.githubusercontent.com/46597093/147957865-9255f077-50c3-4aee-9e08-24babc02fcab.jpg)

Screenshot from [Geo Traveler Genshin Impact Fandom page](https://genshin-impact.fandom.com/wiki/Traveler_(Geo))

Elemental Skill or Burst:
Talent level 1 → 2 requires 3 Teachings of Prosperity
Talent level 6 → 7 requires 4 Philosophies of Gold
Talent level 9 → 10 requires 16 Philosophies of Gold
