### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Arhorn** [MadeBaruna/paimon-moe#208]
When Import Wish History
![image](https://user-images.githubusercontent.com/29491919/148201493-41f5f2ea-a777-484d-bd87-91b4cb2065c5.png)

**Comment by MadeBaruna** [comment]
can you try again?

**Comment by Efreeto** [comment]
I thought I had the same error, but mine was fixed after I realized I included the text "OnGetWebViewPageFinish:" before "https://webstatic-sea..." in the text box. I hope the OP had a similar issue.

It'd be nice to have a less-generic error message since user mistakes like this must be common.
