### ISSUE TITLE
Error 500: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by Blackcatz1911** [MadeBaruna/paimon-moe#209]
Error since today: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

![image](https://user-images.githubusercontent.com/3258015/148202976-9d4cb27b-8663-4669-9851-cc93fb9cbb9d.png)
![image](https://user-images.githubusercontent.com/3258015/148203037-90032dd9-79a7-47ae-bcd2-6e43fc396fa2.png)

**Comment by MadeBaruna** [comment]
can you try to press ctrl+f5, the cache might stuck

**Comment by Blackcatz1911** [comment]
Already tried that. Cleared the whole app cache, but no success.

**Comment by MaxSavini** [comment]
Same problem. Tried to clear cache, reset account in settings - nothing happened.

**Comment by MadeBaruna** [comment]
You can try to press this to clear the cache, its different based on the browser
- CTRL+F5
- SHIFT+F5
- CTRL+SHIFT+R

**Comment by Blackcatz1911** [comment]
Yes I know that and on top I cleared everything with this: 
![image](https://user-images.githubusercontent.com/3258015/148207006-763d8c94-4c69-482d-a9f2-a8263b66d6aa.png)

**Comment by MadeBaruna** [comment]
Yeah I just cleared the cache from the server, should be working as usual (maybe you need to wait for some minutes)

**Comment by Blackcatz1911** [comment]
It's working again for me. Thank you for looking into this!
