### ISSUE TITLE
Not calculating resin for EXP books

### ISSUE THREAD

**Issue by speedisparrow** [MadeBaruna/paimon-moe#22]
The todo list does not calculate the amount of resin required to farm exp books. Under the resin section it does not say anything about exp books
![image](https://user-images.githubusercontent.com/75000094/113635789-1e86b380-9626-11eb-8c36-4860e395c587.png)

**Comment by MadeBaruna** [comment]
It's should have calculate resin for talent book, can you share some screenshot please?

And please separate the google drive issue to a new issue, thanks!

**Comment by speedisparrow** [comment]
Edited it. I meant to say exp books not talent books.

**Comment by MadeBaruna** [comment]
Duplicate of #10
