### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by nikachuuu** [MadeBaruna/paimon-moe#220]
when I uploaded new prayers, they went into the negative. the site doesn't see any new characters.
![DNhR3z_Kw6k](https://user-images.githubusercontent.com/98415492/151024541-edac16dd-381d-4f11-b436-ecb24260674f.jpg)

**Comment by MadeBaruna** [comment]
Try to enable this and import again 
![image](https://user-images.githubusercontent.com/2796366/151222957-a2762ec5-aeab-402c-81e2-d9988a3e7f08.png)
