### ISSUE TITLE
Synchronization on slow network

### ISSUE THREAD

**Issue by zvxayr** [MadeBaruna/paimon-moe#222]
Data on achievements can be lost when the network is slow.

What happened on my case is that I accidentally ticked one box before my data is loaded. Shortly after, synchronization started, overwriting all my data to a blank state, save for the box I ticked.

**Comment by MadeBaruna** [comment]
This is kinda hard to check, will see what can I do

**Comment by utopiatopia** [comment]
I've been able to replicate this reliably. @MadeBaruna

1. Open Chrome DevTools
2. Open "Network"
3. Change "No Throttling" to "Slow 3G".
4. Open Console
5. Sign in with Google Drive
6. Modify data after you see "reading remote file now" but before "get file res"
7. Data loss upon next Drive sync

This seems to be a race condition in [DataSync.svelte](https://github.com/MadeBaruna/paimon-moe/blob/67c4eb95c87c4b453ecc71036c18e40d0b1acaa8/src/components/DataSync.svelte#L201) at line 201. I suggest you make getting Drive and Local data synchronous. I would fix it, however I can't compile the project.

**Comment by MadeBaruna** [comment]
Thanks for your repro! Will fix it soon
