### ISSUE TITLE
Doesn't show the character I have

### ISSUE THREAD

**Issue by Valoween** [MadeBaruna/paimon-moe#223]
From https://paimon.moe/characters I have Aloy since long time ago but the website show that I don't have
![Capture](https://user-images.githubusercontent.com/98998161/152466421-dcb282ea-ee13-43f6-aedf-49e27cb1e1cb.PNG)

**Comment by npanuhin** [comment]
> Constellation count is calculated from your Wish History data.

Since you didn't get Aloy **from the wish system**, website won't recognize her.

> But you can edit it manually by pressing the pencil icon beside the character name.
