### ISSUE TITLE
Incorrect text: 5-star may be 4-star?

### ISSUE THREAD

**Issue by TianSalt** [MadeBaruna/paimon-moe#225]
![无标题](https://user-images.githubusercontent.com/29042755/154394906-ea06a5ff-c4cf-4c2e-891f-be25a6814064.png)
All languages may have this problem.

**Comment by MadeBaruna** [comment]
Fixed https://github.com/MadeBaruna/paimon-moe/commit/49e2be50aff28530ed82c492273f2f230cdfd848
