### ISSUE TITLE
Incorrect achievement version

### ISSUE THREAD

**Issue by linningmii** [MadeBaruna/paimon-moe#226]
Found that all v2.5 achievements have been labeled v2.4.
![image](https://user-images.githubusercontent.com/14858674/154395292-15687db8-25b5-4c8e-867f-78c0a46613a8.png)

Pretty convinced this is a v2.5 achievement because it's related to new battle of Raiden Shogun 
![image](https://user-images.githubusercontent.com/14858674/154395298-040d0509-cb86-4ad8-98b5-355a32f11dd4.png)

**Comment by MadeBaruna** [comment]
Fixed https://github.com/MadeBaruna/paimon-moe/commit/755ad329f360c27c24b29e52f4db63920f15c901 & https://github.com/MadeBaruna/paimon-moe/commit/49e2be50aff28530ed82c492273f2f230cdfd848
