### ISSUE TITLE
Sorting by character name only works in English

### ISSUE THREAD

**Issue by Vaskass** [MadeBaruna/paimon-moe#236]
Sorting characters by name works in English, and then translates to another language.
So sorting by name does not work in another language.
In English:
![image](https://user-images.githubusercontent.com/46313746/159213239-0c09c631-67e7-4332-b164-9634ac1de39b.png)
In Russian:
![image](https://user-images.githubusercontent.com/46313746/159213336-517f4adc-e68d-4aaf-9ec5-deb612340288.png)
The same result, in the Russian localization sorting is not correct

**Comment by MadeBaruna** [comment]
Will see if I can do something about it

**Comment by Vaskass** [comment]
Also Ayaka and Ayato, even in english not in alphabetical order.

**Comment by MadeBaruna** [comment]
> Also Ayaka and Ayato, even in english not in alphabetical order.

![image](https://user-images.githubusercontent.com/2796366/160751335-857f4a47-adb8-4101-b579-8d06aedb3472.png)
it is sorted?

**Comment by Vaskass** [comment]
![image](https://user-images.githubusercontent.com/46313746/160751495-bd733852-7bb7-4a51-944c-c95799f09c3f.png)
I mean in the whole list. They are somewhere in between the characters with letters K, not at the top of the list with letters A.

**Comment by MadeBaruna** [comment]
Yeah its sorting by the first name
