### ISSUE TITLE
[Issue] wish tally graph is auto extending 

### ISSUE THREAD

**Issue by RaSan147** [MadeBaruna/paimon-moe#238]

**Comment by RaSan147** [comment]
https://user-images.githubusercontent.com/34002411/160061322-6a603ac4-3642-4309-ba4c-69ce2bb4a579.mp4

On this page: https://paimon.moe/wish/tally/?id=300021

**Comment by MadeBaruna** [comment]
Is this on chrome browser? because I can't replicate it on my browser

**Comment by RaSan147** [comment]
Its on Firefox, rechecking....

**Comment by RaSan147** [comment]
Issue exists on Firefox but not in chrome

**Comment by MadeBaruna** [comment]
Can't reproduce on firefox 98, can you tell me your firefox version please? thanks

**Comment by RaSan147** [comment]
98.3.0

*couldn't post video here
https://youtu.be/E5DSzDbV2kU

**Comment by MadeBaruna** [comment]
Do you have any extension installed?

**Comment by RaSan147** [comment]
Yes i had but unistalling them makes no change 🤔🤔 should i reinstall Firefox? 😵😵😵 All my data and log ins 🚮
Nope won't dare to do that.....

**Comment by RaSan147** [comment]
Installing firefox nightly or some other....

**Comment by RaSan147** [comment]
https://user-images.githubusercontent.com/34002411/160478679-a4719c5b-73c1-43fb-85ee-5ccc25ff891b.mp4

Fresh installed ff nightly (v 100) still issue exists

**Comment by MadeBaruna** [comment]
Hmm the problem might be specific for your phone resolution/dpi, can you tell what's is your phone?

**Comment by RaSan147** [comment]
Realme 5i (developer mode disabled)
