### ISSUE TITLE
Apakah data riwayat gacha setiap pemain dikoleksi di database?

### ISSUE THREAD

**Issue by satyakresna** [MadeBaruna/paimon-moe#24]
Halo @MadeBaruna, salam kenal dan terima kasih sudah menyediakan tool untuk mengekspor data riwayat gacha pemain Genshin Impact. Saya terbantu dengan hal ini. Saya mau tanya apakah data riwayat gacha setiap pemain dikoleksi di database server pribadi? Jika iya, mengapa demikian?

**Comment by satyakresna** [comment]
Sepertinya saya melewatkan sesi FAQ gacha history wish di website paimon.moe, dari website tersebut menyatakan bahwa tidak menyimpan history wish di database server. Terima kasih informasinya. 🙏

**Comment by MadeBaruna** [comment]
Ada update untuk global gacha wish tally, mungkin bisa baca FAQ nya lagi
