### ISSUE TITLE
我常驻池有两个金，但是说我只有一个金

### ISSUE THREAD

**Issue by Dongyifengs** [MadeBaruna/paimon-moe#240]
![Uploading Screenshot_2022-03-29-14-52-53-654_com.android.chrome.jpg…]()

**Comment by toadsworth-jr** [comment]
Can you please report the issue in English? Some contributors cannot speak Chinese, so we appreciate it if you could. :)

**Comment by MadeBaruna** [comment]
Sorry cannot see the screenshot

**Comment by Champagne0418** [comment]
He said he got two 5-stars in standard wish, but only one appeared in wish counter.
