### ISSUE TITLE
Weird name changing to qiqi??

### ISSUE THREAD

**Issue by Amoodaa** [MadeBaruna/paimon-moe#242]
gradually changes from
Right history:
![image](https://user-images.githubusercontent.com/8256872/161232398-ebaa6d9e-132a-4e86-ade5-44f3f1485fa5.png)

Semi wrong 
![image](https://user-images.githubusercontent.com/8256872/161232479-03ed2855-a284-4e70-9f78-fe0e8f47d0a1.png)
Completely wrong

![image](https://user-images.githubusercontent.com/8256872/161232347-aedc4c01-a808-483e-910c-a816b7b214ff.png)
Automatically fixes itself after a while back to the first image

**Comment by Amoodaa** [comment]
https://youtu.be/d1K36S3Kgg8

**Comment by toadsworth-jr** [comment]
Was that an April Fool's Joke?

**Comment by MadeBaruna** [comment]
Yes that is an April fools joke 🤣

**Comment by Amoodaa** [comment]
HAHA OK
