### ISSUE TITLE
why mobile phone cannot sign in Google?

### ISSUE THREAD

**Issue by hideonbush-cell** [MadeBaruna/paimon-moe#243]
![Screenshot_20220401_180554_com vivo browser](https://user-images.githubusercontent.com/68937832/161243777-95997073-a7f8-4e9a-b4c3-6db64ff7a90c.jpg)
![Screenshot_20220401_180606_com vivo browser](https://user-images.githubusercontent.com/68937832/161243710-99a6fb63-8252-4cc5-9559-733468cd0821.jpg)

**Comment by MadeBaruna** [comment]
related to china region
