### ISSUE TITLE
Character Event Wish (Молитва события персонажа)

### ISSUE THREAD

**Issue by AsuraTyan** [MadeBaruna/paimon-moe#244]
Problems with the history of the received characters. Проблемы с историей полученных персонажей.
In the beginning, all the characters become Qi Qi, but after that everything returns to normal. But there was no such problem before.В начале все персонажи становятся Ци Ци, но после все возравщается в норму. Но раньше такой проблемы не было.
![Без имени](https://user-images.githubusercontent.com/102826797/161320940-5eea5cc1-ca95-4027-8c34-3ede527bca7d.png)

**Comment by AsuraTyan** [comment]
![Без имени](https://user-images.githubusercontent.com/102826797/161321125-7d83871b-fec9-43ec-b2f9-5d86ff2dedd2.png)
After some time.

**Comment by toadsworth-jr** [comment]
I think it was an April Fool's Joke.
Sadly, I wasn't there to see it in it's full glory...
