### ISSUE TITLE
Long character name not display properly in Korean

### ISSUE THREAD

**Issue by vallisneria** [MadeBaruna/paimon-moe#255]
Sorry for my poor English

# Problem
Not display properly long character name like 카에데하라 카즈하(Kaedehara Kazuha), 카미사토 아야카(Kamisato Ayaka), 카미사토 아야토(Kamisato Ayato) and 산고노미야 코코미(Sangonomiya Kokomi) in [characters page](https://paimon.moe/characters/) with grid view.

![image](https://user-images.githubusercontent.com/55619096/164177458-64abad11-ca9c-4acf-974d-7b8df771490f.png)
For example Kazuha's name display only 즈하 not 카즈하.

# Error Reproduction
- Firefox 99.0.1
- Change website language to 🇰🇷한국어

# Proposal
I think you can add [`word-break: keep-all`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) style to name.

**Comment by MadeBaruna** [comment]
Fixed on 5b0ea25277093445e2ba46a296968d57cb2b5050
