### ISSUE TITLE
Find an empty locale item value, please fill in.

### ISSUE THREAD

**Issue by ywtesi** [MadeBaruna/paimon-moe#262]
This is a low-priority issue.

Missing translation text (zh-cn) for **_"Primordial Jade Cutter"_** on **Wish Counter** page, it looks weird.
I know other empty items are deprecated, but this one is really in the stable game version.
I found it shows correct on **Weapons** page, so it's not a translation problem, just missing value somewhere.

I have checked the source code, the value of **_"Primordial Jade Cutter"_** in **_src/locales/items/zh.json_** is empty.
(only zh.json miss it)

(Actually I'm not sure whether this file is related to Wish Counter or not.)

In Simplified Chinese, it is【磐岩结绿】, just like the name in **_src/data/weapons/zh.json_**

![11](https://user-images.githubusercontent.com/9999092/171743983-31f2f9f9-8cee-41d8-abfc-d1965896daf8.png)

**Comment by MadeBaruna** [comment]
Fixed in 999584058ed7e93e201d7d1a2b346f7686e2840f
