### ISSUE TITLE
[Bug] Numbers of AR and WL are not shown on Chrome 102, Windows 11

### ISSUE THREAD

**Issue by lakejason0** [MadeBaruna/paimon-moe#267]
![image](https://user-images.githubusercontent.com/36039861/173214068-9899bffc-c7db-4a87-9b36-6b8824a8d520.png)
HTML inspection indicates that the numbers are there, only visually not shown

**Comment by VoyagerGould** [comment]
Same with me. If I switch language to Simplified Chinese or Traditional Chinese, numbers of AR and WL are not shown. 
Chrome 102.0.5005.115， Windows 10 Enterprise LTSC 1809.

**Comment by lakejason0** [comment]
> Same with me. If I switch language to Simplified Chinese or Traditional Chinese, numbers of AR and WL are not shown. Chrome 102.0.5005.115， Windows 10 Enterprise LTSC 1809.

It seems to be that the string is too long for these to show. However Chinese do not use these abbrev. so idk what to do as a translator.

**Comment by toadsworth-jr** [comment]
My guess for a fix is to make the text box a fixed size.
Or they could also be those "counter" text boxes, with the arrow buttons and all that.
