### ISSUE TITLE
Import failed!

### ISSUE THREAD

**Issue by Drakerion** [MadeBaruna/paimon-moe#277]
Hi.

When I try to import mu xlxs file, it shows error.-

I tried with my 4 backups and all gives same error and no data is imported :(
Am i doing something wrong?
![image](https://user-images.githubusercontent.com/109035178/178152954-93214416-36dd-49d1-8d13-47669302cb84.png)

**Comment by MadeBaruna** [comment]
To import excel go to https://paimon.moe/wish -> setting button on the top -> excel import
