### ISSUE TITLE
[Bug/Suggestion] Manual input overridden when using auto import for wishes

### ISSUE THREAD

**Issue by tiffanynwyeung** [MadeBaruna/paimon-moe#279]
When using "Auto Import" to automatically import wishes, manual inputs for previous, locally-stored wishes is currently overridden such that all values are reset to 1 as their pity. This is because manual input is not considered in `src/routes/wish/import.svelte`, where the logic in the `processWishes` function creates an array of both newly imported wishes and previous local wishes. If a manually-imported wish is counted, and only legendary wishes are added, it will count the legendary wish as exactly 1 as there are no other rare or epic wishes "padding" the count. 

A potential solution would be to pass in `manualInput` as a parameter so you can create a check to see whether the wish pity was set already, like so:

```
if (rarity === 5) {
  latestLegendary = combined[i];
  if (manualInput) {
    combined[i].pity = manualInput;
  } else {
    combined[i].pity = legendary;
  }
  legendary = 0;
} else if (rarity === 4) {
  latestRare = combined[i];
  if (manualInput) {
    combined[i].pity = manualInput;
  } else {
    combined[i].pity = rare;
  }
  rare = 0;
} else {
  combined[i].pity = 1;
}
```

**Comment by MadeBaruna** [comment]
Thanks, been looking the cause of the pity reset to 1! Will add a fix soon
