### ISSUE TITLE
[Feature request/suggestion] Improvement to wishes Global Ranking

### ISSUE THREAD

**Issue by kawakom** [MadeBaruna/paimon-moe#285]
Suggestion to add statistics for global ranking for each banner type for the **most recent sixth months**. The all-time global rankings may be skewed due to (1) old players joining Paimon.moe late and having missing data or (2) players who quit using Genshin or Paimon.moe (and having their wish counts frozen). 

An additional tab/toggle option for switching between all-time and the most recent sixth months of wish history could be useful for players to understand their ranking.

**Comment by MadeBaruna** [comment]
The submitted wish stats already the recent 6 month only
