### ISSUE TITLE
New Wish History Interface doesn't seem to work with the getlink_global.ps1 Script Anymore

### ISSUE THREAD

**Issue by cindrmon** [MadeBaruna/paimon-moe#296]
Since the v3.0 Update, I noticed that the Wish History Interface is updated, and alongside it, the script used for scraping the Wish History to update the Paimon.moe Wish Statistics doesn't seem to work anymore. It just says taht the wish history url cannot be found.\

Here is a pic of the new wish history interface (I'm using a dual-monitor setup to also show you the output of the current script):

![Screenshot (107)](https://user-images.githubusercontent.com/37018771/186391713-1a8b5851-8fac-498f-b5d0-45e3a69f0bcb.png)

**Comment by MadeBaruna** [comment]
https://bit.ly/3QKFLEQ

**Comment by cptmacp** [comment]
it dont seem to update the history far back.

it says lifetime pull 70 , which is not the case for me .

**Comment by MadeBaruna** [comment]
Yeah it can only fetch 6 months back

**Comment by cindrmon** [comment]
> https://bit.ly/3QKFLEQ

are you sure this is safe? will this process not get me banned or anything? just making sure...

**Comment by cindrmon** [comment]
> it dont seem to update the history far back.
> 
> it says lifetime pull 70 , which is not the case for me .

isn't it supposed to append the data with already existing data from paimon.moe, assuming you append the data for every time you update your wish history on the website?

**Comment by MadeBaruna** [comment]
> > https://bit.ly/3QKFLEQ
> 
> are you sure this is safe? will this process not get me banned or anything? just making sure...

Should be safe, it doesn't read/write anything to the game memory

**Comment by ArshhGill** [comment]
/genshin/event/e20... is on localhost for my instance. Changing the URL doesn't work either.

**Comment by cptmacp** [comment]
> /genshin/event/e20... is on localhost for my instance. Changing the URL doesn't work either.

you prob doing something wrong then

i tried it few hours ago and its working fine.

try to restart the app and again press f3 -> history

**Comment by kazerniel** [comment]
> https://bit.ly/3QKFLEQ

Is this only a temporary solution? Ie. will there be a way to auto-import without having to install a new program on my PC?

**Comment by MadeBaruna** [comment]
> > https://bit.ly/3QKFLEQ
> 
> Is this only a temporary solution? Ie. will there be a way to auto-import without having to install a new program on my PC?

Until someone find a way without installing stuff

**Comment by rodrigo-apoc** [comment]
Same problem here

**Comment by zhoeryamh** [comment]
> https://bit.ly/3QKFLEQ
Don't forget add **#/log** after copying the url.

in my case, the url structure is the same, but the captured url isn't a complete like the old **output_log.txt**
![image](https://user-images.githubusercontent.com/46564676/186541457-8580713e-a192-487c-b251-d08e64fcdd01.png)

**Comment by jogerj** [comment]
[I made a workaround that grabs the URL from cache](https://gist.github.com/jogerj/0339e61a92e0de2e360c5212a94854e8#file-get_wish_url_from_cache-ps1). See if anyone can help test it (global only for now)

```powershell 
iex ((New-Object System.Net.WebClient).DownloadString('https://gist.githubusercontent.com/jogerj/0339e61a92e0de2e360c5212a94854e8/raw/6ddd4d2d7f7feff3d25e767a6272ff48ba1e9cd2/get_wish_url_from_cache.ps1'))
```

**Comment by PrimeCicada** [comment]
I managed to find the url still logged on the local machine, it's just in another folder now. Switching in the code for grabbing the URL should allow it to work

    $base = "$Env:Programfiles\Genshin Impact\Genshin Impact Game\GenshinImpact_Data\webCaches\Service Worker\CacheStorage\f944a42103e2b9f8d6ee266c44da97452cde8a7c"
    $file = "00d9a0f4d2a83ce0_0"

    $folder = Get-ChildItem $base | sort -Property LastWriteTime -Descending | select -First 1
    $content = Get-Content "$($folder.FullName)\00d9a0f4d2a83ce0_0" | Select-String -Pattern 'https://webstatic-sea.hoyoverse.com/genshin/event/e20190909gacha-v2/'
    $url = $content[1].ToString()
    $match = $logs -match "https.*log"
    if (-Not $match) {
        Write-Host "Cannot find the wish history url! Make sure to open the wish history first!" -ForegroundColor Red
        exit
    }

**Comment by jogerj** [comment]
@PrimeCicada nice find, doesn't require a third-party tool either

**Comment by PrimeCicada** [comment]
Yeah. I didn't wanted to make too much changes to the existing code so I hoped the url is still being logged somewhere, and it came true. I wanted to incorporate your code for getting the installation path more reliably, but had met the same issue where there was no installpath, which you had just addressed.

**Comment by driftywinds** [comment]
> 

This doesn't seem to work

**Comment by driftywinds** [comment]
> [I made a workaround that grabs the URL from cache](https://gist.github.com/jogerj/0339e61a92e0de2e360c5212a94854e8#file-get_wish_url_from_cache-ps1). It's less intrusive and safer than Fiddler. See if anyone can help test it (global only for now)
> 
> ```powershell
> iex ((New-Object System.Net.WebClient).DownloadString('https://gist.githubusercontent.com/jogerj/0339e61a92e0de2e360c5212a94854e8/raw/6ddd4d2d7f7feff3d25e767a6272ff48ba1e9cd2/get_wish_url_from_cache.ps1'))
> ```
> 
> path location in chinese version might be different, will need info regarding this

The doesn't seem to work

**Comment by jogerj** [comment]
I've incorporated [this better method](#issuecomment-1227058374) from @PrimeCicada into my script and added some workarounds for getting the Genshin install path. It should work now
```powershell
iex ((New-Object System.Net.WebClient).DownloadString('https://gist.githubusercontent.com/jogerj/0339e61a92e0de2e360c5212a94854e8/raw/6ddd4d2d7f7feff3d25e767a6272ff48ba1e9cd2/get_wish_url_from_cache.ps1'))
```

**Comment by MadeBaruna** [comment]
Updated the script here: https://gist.github.com/MadeBaruna/1d75c1d37d19eca71591ec8a31178235
thanks to @jogerj  and @PrimeCicada :)

**Comment by toadsworth-jr** [comment]
Question, the tutorial for Android platforms concerning proxies on wifi will still let me connect to the game normally, right?
I mean, it's tedious to repeatedly remove and reinsert all the values back in if you want to (re)import new wishes if that was the case.

**Comment by MadeBaruna** [comment]
> Question, the tutorial for Android platforms concerning proxies on wifi will still let me connect to the game normally, right? I mean, it's tedious to repeatedly remove and reinsert all the values back in if you want to (re)import new wishes if that was the case.

Well you need to disable the proxy after getting the link
