### ISSUE TITLE
Suggestion: Add supported import method

### ISSUE THREAD

**Issue by Chromartha** [MadeBaruna/paimon-moe#308]
I've been using "Genshin wish Export" for two years  (which also on github https://github.com/biuuu/genshin-wish-export)
Just to ask if it's possible to make it supported on your website for importing logger.

Thank you

**Comment by MadeBaruna** [comment]
It is already supported, its on https://paimon.moe/wish -> setting button on the top -> Import From Excel -> TakaGG Gacha Export (well I need to rename it to Biuuu instead)

**Comment by toadsworth-jr** [comment]
I presume that the reason of renaming it to Biuuu is because that TakaGG no
longer exports wish history?

**Comment by MadeBaruna** [comment]
Yeah since the biuuu version is translated to english already, takagg deleted the repo

**Comment by Chromartha** [comment]
thanks for replying.
Also, about how many time does it take to import?
I've wait for 10 minute after drag it into Excel importer on website but it just says processing

**Comment by MadeBaruna** [comment]
> thanks for replying. Also, about how many time does it take to import? I've wait for 10 minute after drag it into Excel importer on website but it just says processing

should be instant, can you send the excel file? maybe the format changed

**Comment by Chromartha** [comment]
[Genshin wish logger_20220910_185642.xlsx](https://github.com/MadeBaruna/paimon-moe/files/9542517/Genshin.wish.logger_20220910_185642.xlsx)

Excel file here. It's originally traditional Chinese but I made it into English.
or maybe that's the problem. If is, I can just wait for other language being allowed.

**Comment by MadeBaruna** [comment]
> [Genshin wish logger_20220910_185642.xlsx](https://github.com/MadeBaruna/paimon-moe/files/9542517/Genshin.wish.logger_20220910_185642.xlsx)
> 
> Excel file here. I can't find where to private message so I just put here. It's originally traditional Chinese but I made it into English. or maybe that's the problem. If is, I can just wait for other language being allowed.

do you have the original file? I want to add support for other language

**Comment by Chromartha** [comment]
> > [Genshin wish logger_20220910_185642.xlsx](https://github.com/MadeBaruna/paimon-moe/files/9542517/Genshin.wish.logger_20220910_185642.xlsx)
> > Excel file here. I can't find where to private message so I just put here. It's originally traditional Chinese but I made it into English. or maybe that's the problem. If is, I can just wait for other language being allowed.
> 
> do you have the original file? I want to add support for other language

[原神祈願紀錄_20220911_234624.xlsx](https://github.com/MadeBaruna/paimon-moe/files/9542924/_20220911_234624.xlsx)

Here is original file.
Thank you very much.

**Comment by TremblingMoeNew** [comment]
> > [Genshin wish logger_20220910_185642.xlsx](https://github.com/MadeBaruna/paimon-moe/files/9542517/Genshin.wish.logger_20220910_185642.xlsx)
> > Excel file here. I can't find where to private message so I just put here. It's originally traditional Chinese but I made it into English. or maybe that's the problem. If is, I can just wait for other language being allowed.
> 
> do you have the original file? I want to add support for other language

By the way, some Chinese developers has drawn up a format standard of wish log files called _the Uniformed Interchangeable Gacha Log Format Standard_ or _the UIGF standard_ in short(I prefer to call it "the universal format").
It's easy to process and it's a better format for wish log exchange.
_Genshin Wish Export_ support the JSON variant of this format but currently only for Chinese users. Switch its language to simplified chinese then  would have a "导出JSON" (Export JSON) button on the settings panel.

**Comment by MadeBaruna** [comment]
> > > [Genshin wish logger_20220910_185642.xlsx](https://github.com/MadeBaruna/paimon-moe/files/9542517/Genshin.wish.logger_20220910_185642.xlsx)
> > > Excel file here. I can't find where to private message so I just put here. It's originally traditional Chinese but I made it into English. or maybe that's the problem. If is, I can just wait for other language being allowed.
> > 
> > 
> > do you have the original file? I want to add support for other language
> 
> By the way, some Chinese developers has drawn up a format standard of wish log files called _the Uniformed Interchangeable Gacha Log Format Standard_ or _the UIGF standard_ in short(I prefer to call it "the universal format"). It's easy to process and it's a better format for wish log exchange. _Genshin Wish Export_ support the JSON variant of this format but currently only for Simplified Chinese users. Switch its language to simplified chinese then would have a "导出JSON" (Export JSON) button on the settings panel. Suggest to add support for this pretty format.

well if anyone can send me the file, I can try to support it

**Comment by MadeBaruna** [comment]
@Chromartha I have added support for other language file, please try it :)

**Comment by Chromartha** [comment]
> @Chromartha I have added support for other language file, please try it :)

Thank you very much! I have successfully imported my record.

btw, I wonder is there any way to count my times of winning 50:50?
It my because biuuu's record doesn't count that so after I imported it, my global rank doesn't show that.

**Comment by Chromartha** [comment]
> > @Chromartha I have added support for other language file, please try it :)
> 
> Thank you very much! I have successfully imported my record.
> 
> btw, I wonder is there any way to count my times of winning 50:50? It might because biuuu's record doesn't count that so after I imported it, my global rank doesn't show that.

It seems did be recorded but not showing in global rank section
![螢幕擷取畫面 2022-09-20 152442](https://user-images.githubusercontent.com/113240967/191193750-ac4a9075-01ac-496b-a264-ddac7ef77
![螢幕擷取畫面 2022-09-20 152504](https://user-images.githubusercontent.com/113240967/191193764-5606201b-f487-470c-8ba1-7723e055db12.jpg)
b9e.jpg)

**Comment by MadeBaruna** [comment]
> > @Chromartha I have added support for other language file, please try it :)
> 
> Thank you very much! I have successfully imported my record.
> 
> btw, I wonder is there any way to count my times of winning 50:50? It might because biuuu's record doesn't count that so after I imported it, my global rank doesn't show that.

You need to do auto import first

**Comment by Chromartha** [comment]
> > > @Chromartha I have added support for other language file, please try it :)
> > 
> > 
> > Thank you very much! I have successfully imported my record.
> > btw, I wonder is there any way to count my times of winning 50:50? It might because biuuu's record doesn't count that so after I imported it, my global rank doesn't show that.
> 
> You need to do auto import first

I tried that but it disappeared after I imported my old record

**Comment by MadeBaruna** [comment]
> > > > @Chromartha I have added support for other language file, please try it :)
> > > 
> > > 
> > > Thank you very much! I have successfully imported my record.
> > > btw, I wonder is there any way to count my times of winning 50:50? It might because biuuu's record doesn't count that so after I imported it, my global rank doesn't show that.
> > 
> > 
> > You need to do auto import first
> 
> I tried that but it disappeared after I imported my old record

well you need to import the excel first, then auto import

**Comment by Chromartha** [comment]
Got it. It works
Thank you for all your assistance.
