### ISSUE TITLE
[bug] Incorrect DENDRO MC talent book assignment?

### ISSUE THREAD

**Issue by tomkoku** [MadeBaruna/paimon-moe#311]
When buying Battle Pass i choose philosophies of Admonition for my MC Dendro, based on:
```
https://paimon.moe/items
DENDRO MC -> Admonition
```
Then I was suprised seeing in game:
`DENDRO MC -> Praxis`

Could You fix it? : )

Thank You!

**Comment by tomkoku** [comment]
@MadeBaruna Thanks Mate for quick reaction : )
However, sth goes wrong - now all MC Travelers need all talents books :>

**Comment by MadeBaruna** [comment]
> @MadeBaruna Thanks Mate for quick reaction : ) However, sth went wrong - now all MC Travelers need all talents books :>

Yes MC use multiple kind of talent books for every level

**Comment by tomkoku** [comment]
@MadeBaruna Wow - its true indeed :P
Every day something new - thanks : )

BTW, I am Angular developer - maybe there are some areas/issues/features where I could help/contribute?
