### ISSUE TITLE
please help:(

### ISSUE THREAD

**Issue by n1BBa** [MadeBaruna/paimon-moe#318]
Is it possible to restore the prayer counter data if I cleared the browser cache. I did not backup paimon.moe for my entry. But I have a folder with old browser data. Can I somehow restore my data on the paimon.moe website?

**Comment by toadsworth-jr** [comment]
How old is the old data, exactly? more than 6 months? Earlier than that?

**Comment by n1BBa** [comment]
> How old is the old data, exactly? more than 6 months? Earlier than that?

yes, more 6 month

**Comment by n1BBa** [comment]
everything is fine, I found a solution to the problem with the help of old data
