### ISSUE TITLE
[Suggestion] achievements checker

### ISSUE THREAD

**Issue by JakubKubejko** [MadeBaruna/paimon-moe#32]
Hello. I hope this is correct place to write my thoughts, if not please show me a correct place for this topic or move it.
1. Your project is really great and helpful, you did amazing job.
2. Is there in feedback link any info about account's achievements or is there a way to extract them (let's say from api or something)? If yes - could you make a achievements search, which would really help to find missing achievements (especially from "wonders of the world" section since they are hidden there).
Thanks in advance for your response.

**Comment by MadeBaruna** [comment]
I don't think we can see achievement from the token sadly

**Comment by MadeBaruna** [comment]
But will make a page with the list of achievements and you can check it manually

**Comment by BobbyWibowo** [comment]
Would love it even if we only have that much to be honest ❤️
