### ISSUE TITLE
祈愿记录

### ISSUE THREAD

**Issue by ReFenter** [MadeBaruna/paimon-moe#324]
由于操作失误，导致祈愿记录出错，请问能修改吗？或者在不清除成就的情况下，清除祈愿记录？可以做到吗？

**Comment by toadsworth-jr** [comment]
We only accept issues in English.
No, don't worry. Google Translate is fine, too.

**Comment by lakejason0** [comment]
they would like to only clear the wish history (they accidentally corrupted it), with achievements and so on unaffected.

**Comment by toadsworth-jr** [comment]
In that case, you can do so with manual input.
But do note that it's very tedious as you'd have to delete entries one by one.
