### ISSUE TITLE
 Got falsely banned on Paimon.moe Discord because of rickroll link!

### ISSUE THREAD

**Issue by MizukumaMC** [MadeBaruna/paimon-moe#331]
![Screenshot_20221105-222728_Discord](https://user-images.githubusercontent.com/103873976/200124972-ea783a0f-7755-4908-974c-7cf37190c272.jpg)
![Screenshot_20221105-215609_Discord](https://user-images.githubusercontent.com/103873976/200124994-61a6222c-4a14-4c1d-8dcc-5352ea11b70d.jpg)
 This is not a link to nsfw links but my intention is to bait people on the server to get rickrolled! Mods didn't know what is rickroll and banned me for this stupid reason!
 Rickroll is a harmless prank but people exagrating it too much!

Rickroll link:https://rr.noordstar.me/nahida-loli-hentai-watch-k-1f6b4ce2
![Screenshot_20221105-223932_Kiwi Browser](https://user-images.githubusercontent.com/103873976/200125223-f2f4af8c-51cd-4d8d-b9c7-dbc9b4dbfd1d.jpg)
This is where the link is made and mislead the people tricking that the link is a h**tai video!

I swear that this is not nsfw link and this will redirect you to Rick Astley music!

Please unbanned me! Willing to send ID if you have trust issue!

**Comment by toadsworth-jr** [comment]
This is not an issue for the discord.
Ask him directly about it, this is only for problems _about the service_, not your ban.

**Comment by Deses** [comment]
That's a well deserved ban, if there ever was one.
