### ISSUE TITLE
能否添加一个图片识别功能

### ISSUE THREAD

**Issue by yehuoshun** [MadeBaruna/paimon-moe#336]
类似于椰羊（https://cocogoat.work/）这种，通过图片识别来确定仓库信息

**Comment by lakejason0** [comment]
Please use English when submitting issues.
提交issues时请使用英文。
下方是翻译。
Below is the translation of the original issue.
----
Add an OCR recognition function
it’s like https://cocogoat.work, which uses OCR to import inventory / achievement list and so on.
