### ISSUE TITLE
Timer on Events (Timeline page) doesn't take local time into account

### ISSUE THREAD

**Issue by Maurin3** [MadeBaruna/paimon-moe#34]
In the timeline view, there is a checkbox to see events and banners with our local time.
There is also a timer on each event that represents the time left before the event goes away.
This timer is not accurate when thicking the "Show as local time" checkbox.

I made a video to explain the issue (it may be better than my explanation above, sorry) :

https://user-images.githubusercontent.com/28402592/114926857-22d67c00-9e31-11eb-96f8-80267733fc4b.mp4

**Comment by MadeBaruna** [comment]
Um I think it's already right because the time move too? (unless I miss something)

**Comment by Maurin3** [comment]
I don't know if it's bit more precise but I was talking about the little timer next to the event (on the video it was for the oceanid event) but now it's gone.

The "Show as local time" checkbox was already thicked so it was on the correct time but if I unthick the checkbox, the time left remains the same and is different when you click on the event itself... 

Here is some screenshots with elements highlighted in red :

![Paimon_moe_localtime_timeline](https://user-images.githubusercontent.com/28402592/114996058-c27e2380-9e9e-11eb-80ae-6b6584925710.PNG)

![Paimon_moe_localtime_event](https://user-images.githubusercontent.com/28402592/114996036-bd20d900-9e9e-11eb-9609-55397ce7fc0d.PNG)

![Paimon_moe_gloabltime_timeline](https://user-images.githubusercontent.com/28402592/114996097-ca3dc800-9e9e-11eb-9b94-9bb3fbb79d1e.PNG)

![Paimon_moe_globaltime_event](https://user-images.githubusercontent.com/28402592/114996102-cc078b80-9e9e-11eb-92e3-a0f5932718e6.PNG)
