### ISSUE TITLE
[BUG] Character card dragging seems to seriously break TCG tab. Can't use it anymore.

### ISSUE THREAD

**Issue by Ilya0S** [MadeBaruna/paimon-moe#354]
What happened: created a deck with just character cards (ABC), opened it, noticed cursor changing to drag icon, decided to try (dragged card of character D into the deck instead of character C). Result: deck with characters ABC, character section is uneditable now, has characters AB with 1, CD without anything. Basically, deck says there are three character cards assigned while tab says that there are only two, which creates some sort of conflict.

Result: no error message, but I can't remove characters A or B, re-add character C, add character D or any other. I also can't use Show Deck button. Whenever I try anything of things above, page freezes until I reload.
What I can: switch major tabs (TCG/Settings/etc.) even when frozen (address bar reflects change, but page changes only on forced page reload), when not frozen I can switch character/action cards tabs, add or remove action cards, click on card to open its menu, change card table size (big or small cards), toggle preview-on-hover on and off as well as trigger it.

**Comment by MadeBaruna** [comment]
To fix broken deck you can open a shared deck (ex: https://paimon.moe/deck/ey6ppcazuw) then you can click the select deck button, then delete it
