### ISSUE TITLE
Account Security

### ISSUE THREAD

**Issue by tyusaa** [MadeBaruna/paimon-moe#4]
Is guaranteed the security of the owner's account who entered the wish data on this website?

**Comment by MadeBaruna** [comment]
What kind of security? If it's about your account getting hacked by me, the answer is never. I never save anything related to your account, the wish data also only saved on your browser (or your google drive)

**Comment by OrangeBonBon** [comment]
How about account security from other people? from what I'm understanding that the link from the feedback only gives temporary keys and your website never saves anything regarding info but is it still possible for other people (hackers) to get personal acc info by any means?

to put it simply, is your website safe? or will you be adding more security in the future?

**Comment by MadeBaruna** [comment]
Yeah I use ssh keys for the cors server, and I checked for any weird behavior everyday. The link were send with https to the server then the result will immediately sent back to the browser, and no keys were lingering around, that should be safe, unless there is a virus on the device (but it's a different story).
