### ISSUE TITLE
Need Character birthday in timeline

### ISSUE THREAD

**Issue by aquadrehz** [MadeBaruna/paimon-moe#400]
I always want to get the mail from my favorite character.
And I check calenr da on this page really often
Could we have a feature to display them?

**Comment by Antosik** [comment]
You can find character birthday on the calendar's page - https://paimon.moe/calendar

![image](https://user-images.githubusercontent.com/4852791/225860483-8c0ac76d-f5b9-4258-8656-6a3168d4eff1.png)

**Comment by aquadrehz** [comment]
Thank. Didn't expected it displayed there.
You can close this issue

**Comment by aquadrehz** [comment]
Thanks. I'm close this issues
