### ISSUE TITLE
Data has been deleted

### ISSUE THREAD

**Issue by JarvisLight** [MadeBaruna/paimon-moe#401]
After clearing the cookies and cache, I accidentally clicked on the data recovery button from the browser, and not from Google drive. All the data is lost and it turns out that the disk is also empty now? Is there a way to recover data from the disk (it was a month old and all 2 years of my wishes and achievements were there)?

**Comment by jogerj** [comment]
Duplicate #318 #327 #335 #339 #378 #391

**Comment by JarvisLight** [comment]
> Duplicate #318 #327 #335 #339 #378 #391

There is no solution. I HAVE the google drive linked to my account, I just chose the wrong option to load the data. Of the two proposed, I chose "new data from the browser" instead of "old data from google drive"

**Comment by WhiteAls** [comment]
> > Duplicate #318 #327 #335 #339 #378 #391
> 
> There is no solution. I HAVE the google drive linked to my account, I just chose the wrong option to load the data. Of the two proposed, I chose "new data from the browser" instead of "old data from google drive"

Unfortunately, your data has been irretrievably destroyed. You selected the wrong option, and the system synchronized empty data to your Google Drive.

I agree that this may not be the best behavior, and it may be worth adding a synchronization check that compares, for example, the data size and issues a large warning with red text. But that is a different topic for a different issue.

**Comment by jogerj** [comment]
There were plenty of warnings, you consented to overwriting your data. There is always the option of downloading both files before proceeding. There's also always the option to export/import a backup from other than Google Drive.

**Comment by LXDMXLDMBX** [comment]
> There were plenty of warnings, you consented to overwriting your data. There is always the option of downloading both files before proceeding. There's also always the option to export/import a backup from other than Google Drive.

UX basics are the bare minimum required when creating any product meant to be used by other people. If you can't handle basic UX, you shouldn't be building products for others in the first place — build stuff only for yourself.
