### ISSUE TITLE
Mobile wish log instruction does not work anymore.

### ISSUE THREAD

**Issue by limeeugenia** [MadeBaruna/paimon-moe#402]
Hey folks,

I was pulling my wish history by your instruction on mobile (I'm using Stream app) and noticed that the log only showed my latest 4 wishes, skipping the around 70 wishes I did before I got Shenhe.

I will try to investigate myself, maybe hoyo now loads them per page and you need to go over several pages, but would be nice if some of you who knows how this works with them can look into this.

Thanks!

**Comment by jogerj** [comment]
Seems about right. Am I understanding you correctly that you put the url in auto import already and it only managed to import 4 wishes?

**Comment by limeeugenia** [comment]
Ok, it's five. Here is what the response:

```
{
"retcode": 0,
"message": "OK",
"data": {
"page": "17",
"size": "5",
"total": "0",
"list": [
{
"uid": "715011077",
"gacha_type": "301",
"item_id": "",
"count": "1",
"time": "2023-02-08 12:12:12",
"name": "Hu Tao",
"lang": "en-us",
"item_type": "Character",
"rank_type": "5",
"id": "1675854360000215977"
},
{
"uid": "715011077",
"gacha_type": "301",
"item_id": "",
"count": "1",
"time": "2023-02-08 12:12:04",
"name": "Emerald Orb",
"lang": "en-us",
"item_type": "Weapon",
"rank_type": "3",
"id": "1675854360000214277"
},
{
"uid": "715011077",
"gacha_type": "301",
"item_id": "",
"count": "1",
"time": "2023-02-08 12:11:55",
"name": "Harbinger of Dawn",
"lang": "en-us",
"item_type": "Weapon",
"rank_type": "3",
"id": "1675854360000213777"
},
{
"uid": "715011077",
"gacha_type": "301",
"item_id": "",
"count": "1",
"time": "2023-02-08 12:11:55",
"name": "Skyrider Sword",
"lang": "en-us",
"item_type": "Weapon",
"rank_type": "3",
"id": "1675854360000213677"
},
{
"uid": "715011077",
"gacha_type": "301",
"item_id": "",
"count": "1",
"time": "2023-02-08 12:11:55",
"name": "Emerald Orb",
"lang": "en-us",
"item_type": "Weapon",
"rank_type": "3",
"id": "1675854360000213577"
}
],
"region": "os_euro"
}
}
```

I'm able to tweak the params in the URL, so I get 20 results max, but it's only 20 last always, since `page` param does not seem to affect the response.

**Comment by limeeugenia** [comment]
And, yeah, I put it into the the auto-import already.

**Comment by jogerj** [comment]
Doesn't matter. The URL you put in is stripped and only the auth token is used. Just give the url unedited to auto import, stop trying to modify it.

**Comment by limeeugenia** [comment]
sure, that was the first thing I attempted since it has always worked previously.
