### ISSUE TITLE
Your local data in this browser is conflicting with the ones stored in the Google Drive!

### ISSUE THREAD

**Issue by nyaashaa** [MadeBaruna/paimon-moe#43]
Hello! Since yesterday, every time I visit the site, I have been shown this message. I deleted my profile and re-entered the data, clean the browser cookies, deleted information from the google disk - all the same, this warning pops up every time. It seems to me that it all started after I manually changed the constellations for some characters.

![2021-04-20_194028](https://user-images.githubusercontent.com/35262779/115433984-d4e6bd00-a210-11eb-978d-14a5b5da9266.jpg)

**Comment by MadeBaruna** [comment]
Thanks for the information, will look into it
