### ISSUE TITLE
Cannot find the wish history url!

### ISSUE THREAD

**Issue by KtuJis** [MadeBaruna/paimon-moe#432]
https://youtu.be/RxX2CqVyzzc

**Comment by FrostLynn** [comment]
I think HV change something on this update so it messed up with this, try method 2 for now, it work for me.

**Comment by nikkehtine** [comment]
Method 2 only keeps showing me `Get-Clipboard: A parameter cannot be found that matches parameter name 'TextFormatType'.`, Method 2 Alt works

**Comment by KtuJis** [comment]
Method 2 does not work.
Method 2 Alt works

**Comment by jogerj** [comment]
Duplicate #431

Solved.
