### ISSUE TITLE
50:50

### ISSUE THREAD

**Issue by gavd99** [MadeBaruna/paimon-moe#440]
Hello there! I am using the Manual Input. As far as I know, for everyone who uses Auto Import there's a percentage of wins of 50:50, but I do not have this. Is it because of the Manual Input? Could you please add this feature to users who use the Manual Input?

<img width="638" alt="Безымянный" src="https://github.com/MadeBaruna/paimon-moe/assets/33306426/5317e9a5-651c-4013-a11f-a1f85f56bfdd">

**Comment by jogerj** [comment]
Run auto import once to recalculate. If it fails, your manual input was incorrect (e.g. Wrong bannet, timestamp, name, etc.)

**Comment by gavd99** [comment]
I tried it with a clear history, there's no mistakes here, but still no 50:50 percentage

https://github.com/MadeBaruna/paimon-moe/assets/33306426/abe93233-9c19-41ea-8a67-a53fe2dca6cf

**Comment by jogerj** [comment]
50:50  isn't calculated unless you run auto-import. It risks throwing errors otherwise when the manual input contains invalid data

**Comment by gavd99** [comment]
That's why I asked if it could be possible to implement this feature for Manual Input too. It's strange to not calculate it at all, even if the input is valid

**Comment by jogerj** [comment]
No, it's invalid as it's missing the 3-star and 4-star wishes in-between.

This is why it never made sense to implement the feature for manual import. The feature has always been a beta feature to begin with.

**Comment by gavd99** [comment]
No, it's literally valid input. 5-stars can drop one by one, it's just very unlikely, but it is possible, therefore the input is valid. Even my friend got two consecutive 5-starts. I could do more ordinary input, the video just would be longer

I understood that this feature is not implemented yet, due to manual import being a beta feature. But there is sense to implement it, as for it is the same wishing history, just a different type of input. Yes, someone could have some mistakes in their input, then there could be some message saying that this calculation could be inaccurate if your input is invalid. Thanks for your time
