### ISSUE TITLE
PC wish import methods not working

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [MadeBaruna/paimon-moe#445]
URL not present in output_log.txt anymore
Can't seem to copy the table from ingame
URL can still be found in the webCache file though

**Comment by My-Name-Is-Jeff** [comment]
For the gist file on method 1, can be fixed by changing the version on 
$cachefile = "$gamedir/webCaches/2.13.0.1/Cache/Cache_Data/data_2"
to

**Comment by diggtrap** [comment]
I'm gonna go on a whim and say that something changed again in 4.0 like it did in 3.0

**Comment by sleepnov4** [comment]
The **Method 1** is not working.
![Screenshot_39](https://github.com/MadeBaruna/paimon-moe/assets/31282709/a88a34db-2459-4642-8385-35782074c8a9)

**Comment by My-Name-Is-Jeff** [comment]
Resolved by 1d11599ab709f44c590b3aec3231ef39804c97ba
