### ISSUE TITLE
Wish import automatically fills in Character Data, but too many constellations...

### ISSUE THREAD

**Issue by ruzuki** [MadeBaruna/paimon-moe#45]
Hello,
I imported my wish data, but it seems to have filled in my data in the Character tab automatically, and some characters have far too many constellations, since I pulled some characters more than 7 times in total. 
There should be a cap on the constellation number so it cant go beyond 6, or at least let us manually lower it. It wont let me lower it, only raise it.

![image](https://user-images.githubusercontent.com/32341576/115788925-2f029200-a379-11eb-9e53-73c059d467b9.png)

**Comment by MadeBaruna** [comment]
It is intentional to let it go beyond 6 :)
For now the data from wish history cannot be increased/decreased
