### ISSUE TITLE
Achivement - The Final Fonta Sea is missing the Tier 2 and 3 version

### ISSUE THREAD

**Issue by Firq-ow** [MadeBaruna/paimon-moe#464]
Currently, the achievement "The Final Fonta Sea" is listed as a single 5 Primogem achievement.

However, this achievement actually has 3 tiers, granting 5 Primogems for each (15 total). Additionally, each tier of the achievement is counted separately, meaning the achievement counts differ between the website and the game (I have all achievements tracked, this is the current status).

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/99767f00-e24f-405e-aab6-71daccd48fb9)

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/af575bf1-4860-4e5d-9093-7fbf2602028e)

I attached screenshots for the tier 2 and 3 version, as well as for the final status.

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/873f0245-4375-40ed-813e-5142388abee6)

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/b7df16f5-1b11-4845-ba43-e8e1b4632a66)

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/e7cd5983-9e06-4b8f-baa3-2f550fdf1439)

The website currently does not reflect the status of the achievement.

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/9d53b02a-1928-4ff8-a4ef-3e5f629e3f6d)

I would expect this to be displayed like the "Zoo Tycoon" achievements

![image](https://github.com/MadeBaruna/paimon-moe/assets/75133068/e1e45478-7ea6-420a-96bb-f502e5dc4a25)

I have the vague guess that this has to do with the fact the achievement always grants 5 Primogems as a reward, making it difficult to separate the tiers (compared to other similar achievements, which usually grant scaling rewards).

**Comment by thomkax** [comment]
link to wiki:
https://genshin-impact.fandom.com/wiki/The_Final_Fonta_Sea

**Comment by thomkax** [comment]
Created a pull request #468

**Comment by Firq-ow** [comment]
Perfect, this can be closed one #468 is merged. Thanks for the MR @thomkax 💜

**Comment by Firq-ow** [comment]
Closing this as MR #468 by @thomkax has been accepted.

Thank you again 💜
