### ISSUE TITLE
Import Data Wrong

### ISSUE THREAD

**Issue by heatedharth** [MadeBaruna/paimon-moe#49]
Am I somehow importing this wrong? I’m on iOS. It’s not showing my wishes from October - Early November and I’m AR55, WL8.
![1DFDC695-9505-4853-9C3A-1DCB47978C24](https://user-images.githubusercontent.com/83228267/116096517-5dcd8080-a677-11eb-844a-3cc5fe720f08.jpeg)
![94E80D1A-B1A7-4CE3-8FE1-66670B2CD492](https://user-images.githubusercontent.com/83228267/116096519-5dcd8080-a677-11eb-9e3f-ad0da3811785.jpeg)

**Comment by MadeBaruna** [comment]
Wishes older than 6 month is deleted from mihoyo server, please check your in game wish history
