### ISSUE TITLE
Update Furina constellation will remove all the constellation of all characters

### ISSUE THREAD

**Issue by AlexLu202** [MadeBaruna/paimon-moe#506]
Update Furina constellation will remove all the constellation of all characters

Step to reproduce

1. Go to Character page
2. Click Furina's image
3. Editing the constellations
4. Save it
5. Go back to Character page
6. Refresh the page

Expected Result: Furina's constellations updated 
Actual Result: All constellations of all characters are gone

**Comment by jogerj** [comment]
Duplicate #466 #480
