### ISSUE TITLE
Yanfei causing error on import

### ISSUE THREAD

**Issue by TimberwolfGalaxy** [MadeBaruna/paimon-moe#51]
I just tried to import my wishes from the feedback page on PC and got the error "Invalid data returned from API" when it tried to import my character event banner pulls. My last roll was Yanfei, who is new and is, I assume, the cause of this error because she is unseen data.

**Comment by MadeBaruna** [comment]
Can you screenshot your ingame wish history page with Yanfei in it?

**Comment by TimberwolfGalaxy** [comment]
Here you go:
![yanfei](https://user-images.githubusercontent.com/40547089/116550208-52fb3180-a8ab-11eb-9b25-0d424cd94dcb.PNG)

**Comment by MadeBaruna** [comment]
Hmm weird, can you try to import again? Someone on discord got a same error, and it works after an hour or so

**Comment by TimberwolfGalaxy** [comment]
It works! Thank you!
