### ISSUE TITLE
Cannot Import weapon banner

### ISSUE THREAD

**Issue by user-u99** [MadeBaruna/paimon-moe#573]
Once I paste the link that I get from sniffing, it processes it but does not recognize the new Nilou weapon banner pulls I did.

I think MHY also changed the link? It has been a while since I last pulled before pulling Nilou's weapon this banner, but I found the link unfamiliar when sniffing it with stream. Perhaps I got the wrong link?

It starts with `<public-operation-hk4e-sg>` instead of `<hk4e-api-os>`

**Comment by darkash** [comment]
> Once I paste the link that I get from sniffing, it processes it but does not recognize the new Nilou weapon banner pulls I did.
> 
> I think MHY also changed the link? It has been a while since I last pulled before pulling Nilou's weapon this banner, but I found the link unfamiliar when sniffing it with stream. Perhaps I got the wrong link?
> 
> It starts with `<public-operation-hk4e-sg>` instead of `<hk4e-api-os>`

It's recently updated on hoyo side
There's PR #572 which should fix the issue

**Comment by user-u99** [comment]
Then I have no idea what could be causing my wishes not to be imported. Thanks.

**Comment by Astroneko404** [comment]
the website extracted starts with "https://gs.hoyoverse.com/genshin/event/e20190909gacha-v3/" now. Did they update the API again?

**Comment by jogerj** [comment]
> the website extracted starts with "https://gs.hoyoverse.com/genshin/event/e20190909gacha-v3/" now. Did they update the API again?

The link you provided is for the web page for wish history. The page calls an API which they recently moved.

Resolved by #572

**Comment by user-u99** [comment]
I tried importing my wishes again today and everything worked fine! Just an update. Thanks to the community for all your help.
