### ISSUE TITLE
Cannot import wish history

### ISSUE THREAD

**Issue by hr951** [MadeBaruna/paimon-moe#575]
"Cannot Find Te Wish History Uluru! Bake Thread and Open the Wish History First!" and the import URL is not displayed.
![bug (1)](https://github.com/user-attachments/assets/46897d45-d2bd-4c77-ae76-5c7fc0bb70f8)

**Comment by jogerj** [comment]
Delete the `webCaches` folder in `GenshinImpact game\GenshinImpact_Data`. Then open wish history again.
![image](https://github.com/user-attachments/assets/a6a4e063-7b3f-42de-99d1-8c9311328b2f)

**Comment by hr951** [comment]
Thank you
