### ISSUE TITLE
Cannot import wish on PC "Connection timeout, please wait a moment and try again later

### ISSUE THREAD

**Issue by mmn6d6d6e** [MadeBaruna/paimon-moe#587]

**Comment by Haloroute** [comment]
I have this error too. I have tried all 3 method. Method 2 returns the correct webpage (which view the wish history). But somehow, paimon.moe is still unable to read.

**Comment by Usvsworld** [comment]
> I have this error too. I have tried all 3 method. Method 2 returns the correct webpage (which view the wish history). But somehow, paimon.moe is still unable to read.

I've tried all three methods too. 

Not sure if this is helpful, but I also noticed it doesn't seem to be able to tell if I'm on the wish page or not. It gives me a link each time even when I made that mistake.

**Comment by Nechigawara** [comment]
I also get this problem.

**Comment by cleaclop** [comment]
I'm also dealing with the same issue, I've done literally everything to try and get it to work but it just gets stuck on processing the beginner wish before saying there's a connection error and to try again later

**Comment by kxxoling** [comment]
Same error here. There's a 502 timeout connection to `https://api.paimon.moe/corsproxy`. Is there anything wrong with the backend?

**Comment by mmn6d6d6e** [comment]
just tried it, now it works

anyone can confirm?

**Comment by Andron77732** [comment]
yes, it is working now

**Comment by jogerj** [comment]
probably server was busy (very usual around new banner launch). Just wait until it's not busy
