### ISSUE TITLE
Can go after C6 in Character form

### ISSUE THREAD

**Issue by Maurin3** [MadeBaruna/paimon-moe#59]
I did a wish in the game today, got Noelle and she was already C6 on my account before that pull... 
I imported my data on Paimon.moe as written and now, I have a Noelle C7 and have a C7 character makes no sense.

The result of my wish in game (see the conversion, this indicates that I have already her in C6):
![noelle](https://user-images.githubusercontent.com/28402592/118188669-08e48500-b441-11eb-8f1f-6d8aec973b97.jpg)

And now, after the importation on Paimon.moe:
![image](https://user-images.githubusercontent.com/28402592/118189149-b8215c00-b441-11eb-87e8-204e7fe74b1c.png)

**Comment by MadeBaruna** [comment]
its intended

**Comment by Maurin3** [comment]
Ok then 😅. Btw, thanks for this beautiful website 😉.
