### ISSUE TITLE
Wish Counter is broken

### ISSUE THREAD

**Issue by nyaashaa** [MadeBaruna/paimon-moe#63]
I imported only new wishes but it imported everything and broke all my stats.

![2021-05-19_073349](https://user-images.githubusercontent.com/35262779/118756980-c07bfb80-b874-11eb-91e9-e496ef126611.jpg)
![2021-05-19_073358](https://user-images.githubusercontent.com/35262779/118756983-c376ec00-b874-11eb-9556-5b337285ecc3.jpg)
![2021-05-19_073406](https://user-images.githubusercontent.com/35262779/118756987-c540af80-b874-11eb-8b4f-0718f98e3bb1.jpg)

**Comment by MadeBaruna** [comment]
Can you join our discord? Need more information

**Comment by nyaashaa** [comment]
I have to go to work; I can to join a Discord only in the evening UTC+3. Also, my English is not very good, so I write slowly, but understand English very well.

**Comment by MadeBaruna** [comment]
No problem, but please go to help & settings then export to excel, then share it to me

**Comment by nyaashaa** [comment]
It gives me an error and export an empty file. But I went to the paimon.moe from my smartphone, there was an old Wish story and I restored it. Also, I downloaded paimon-moe-local-data.json and paimon-moe-drive-data.json and they are different. And I have paimonmoe_wish.xlsx from my smartphone — it’s a good file, but with old Wish story.
I can upload all of it here if it's safe. Or I can upload it to Discord.

![2021-05-19_083448](https://user-images.githubusercontent.com/35262779/118767163-11e0b680-b886-11eb-885d-c10e589d0392.jpg)

**Comment by MadeBaruna** [comment]
I think I have fixed it, but user before this may have to restore the data from the localstorage. But if you have restore the old data, its good now right?

**Comment by nyaashaa** [comment]
Haven't tested it yet, but I think it will be okay if you fix it. I just restored the old data. I was lucky they were on my smartphone. So, you don't need this data anymore?

**Comment by nyaashaa** [comment]
Just checked it out. It looks like everything is fine. Thank you!

![2021-05-19_100154](https://user-images.githubusercontent.com/35262779/118769901-56218600-b889-11eb-9bdf-5be5aab3bee3.png)

**Comment by MadeBaruna** [comment]
Yep, its fine now :)
