### ISSUE TITLE
Character Data

### ISSUE THREAD

**Issue by ShippingTrashAway** [MadeBaruna/paimon-moe#68]
So I'm not all that sure if this is a bug or just something on my part but on my character page its saying that I have Xiangling instead of Beidou. It could be that I _just_ pulled Beidou but its been saying that I've had Xiangling even before I made a wish. It doesn't even say in the logs on the wish banners that I've ever pulled Xiangling. 
![Screenshot_19](https://user-images.githubusercontent.com/85176583/120337056-f8496100-c2c0-11eb-9237-f08a286a1a81.png)
![Screenshot_2021-06-01 Paimon moe](https://user-images.githubusercontent.com/85176583/120337746-963d2b80-c2c1-11eb-982a-433b63008740.png)
![Screenshot_20](https://user-images.githubusercontent.com/85176583/120337836-ab19bf00-c2c1-11eb-846f-34b87e5a0bbf.png)

**Comment by MadeBaruna** [comment]
I added xiangling as default because you get it for free after defeating abyss floor 3

**Comment by ShippingTrashAway** [comment]
Ooh! Sorry 😓 I haven't really done the abyss floors so I never knew that! Thank you anyways!!

**Comment by MadeBaruna** [comment]
no problem :)
