### ISSUE TITLE
Tag Comission Achievement

### ISSUE THREAD

**Issue by as280093** [MadeBaruna/paimon-moe#74]
Currently, All Achievement is as Genshin Achievement list and there is the only way to know if it's based on commission 
so an indication even a tag and option to filter out so.

**Comment by MadeBaruna** [comment]
do you mean a tag to indicate commission achievement?

**Comment by as280093** [comment]
yup

**Comment by tilda** [comment]
i believe *Editorial Opinion*, *Samurai Gourmet*, *Hidden in Plain Sight*,  and *Is There But One Truth...?* are commission achievements as well.

(also, shouldn't this be closed since the tag got added?)
