### ISSUE TITLE
Furnishing room 3 breaks the site

### ISSUE THREAD

**Issue by Mekiah** [MadeBaruna/paimon-moe#76]
When I go to Database > Furnishing > Interior > Room 3, the entire site becomes unresponsive and I see and error in the console.

![image](https://user-images.githubusercontent.com/14081804/121555056-ab603b80-c9e0-11eb-9f84-e59c263dc8a4.png)

**Comment by MadeBaruna** [comment]
can you paste this on the console `JSON.stringify(await localforage.getItem('furnishing'))`
then send the result here

**Comment by Mekiah** [comment]
`"{\"exterior\":{},\"exterior2\":{},\"exterior3\":{},\"exterior4\":{},\"hall\":{},\"room1\":{},\"room2\":{},\"room3\":{\"pine_folding_screen_billowing_sails\":1,\"intricately_carved_calligraphy_table\":1,\"trusty_portable_lamp\":2,\"tavern_rug_home_away_from_home\":1,\"entrance_rug_a_warm_welcome\":1,\"neat_stack_of_books\":1,\"scholars_weariness\":1,\"calligraphy_set_assiduous_calligraphy\":1,\"cloudy_haze_bed\":1,\"large_birch_wardrobe\":1,\"birch_double_drawer_nightstand\":1,\"archivists_treasure_trove\":1,\"exquisite_hourglass_ornament\":1,\"flower_arrangement_sprawling_daybreak\":1,\"outdoor_pine_round_table\":1,\"pine_dining_chair\":1,\"liuli_pavilion_sandbearer_floor_lamp\":1,\"well-worn_sword\":1},\"corridor\":{}}"`
