### ISSUE TITLE
Wrong constellation numbers

### ISSUE THREAD

**Issue by icantthinkofausernam** [MadeBaruna/paimon-moe#79]
I've notice that some of my characters have wrong constellation counts. For example i have a c5 razor but on paimon.moe it says c3. The same goes for barbara and amber who is both c3 and the website says they are only c2

**Comment by envy** [comment]
The wish history is not kept forever, your first wishes are probably not saved anymore by mihoyo and therefore paimon.moe cannot import them.
You can set the number manually if it isn't correct.

**Comment by MadeBaruna** [comment]
Duplicate #55
