### ISSUE TITLE
A small Question

### ISSUE THREAD

**Issue by felixsam359** [MadeBaruna/paimon-moe#86]
1/ Can I host this code on a IDE like replit? 
2/ If so what are the steps in doing so I m little bit confused
3/ Is firebase api free or they charge money

**Comment by MadeBaruna** [comment]
1. I never use it so I don't really know
2. -
3. its free because its only use the notification feature

**Comment by felixsam359** [comment]
Hmm no worries anyways thnx for replying.
I want to know how to run the whole file.

Like in case of python we write ```python main.py``` in console.

What I have to write in console?
