### ISSUE TITLE
add a Resin page 

### ISSUE THREAD

**Issue by Rahman-X** [MadeBaruna/paimon-moe#9]
would be nice to know how many resin left without opening the app , especially on ps4

**Comment by MadeBaruna** [comment]
Do you mean like a timer?

**Comment by iyungrozy** [comment]
it's difficult because it requires synchronization from mihoyo directly

**Comment by fadhluu** [comment]
i guess you cant do it (imposibble for rn), because afaik mihoyo didnt share their api directly

**Comment by Rahman-X** [comment]
> Do you mean like a timer?

yes

**Comment by Rahman-X** [comment]
> i guess you cant do it (imposibble for rn), because afaik mihoyo didnt share their api directly
just input manually how many resin left 
and it will count by itself i think?

**Comment by fadhluu** [comment]
> > i guess you cant do it (imposibble for rn), because afaik mihoyo didnt share their api directly]
> 
> just input manually how many resin left
> and it will count by itself i think?

i guess it can do it if we just input manually, i thought youre referring to "automation" from mihoyo

**Comment by fadhluu** [comment]
> > i guess you cant do it (imposibble for rn), because afaik mihoyo didnt share their api directly]
> 
> just input manually how many resin left
> and it will count by itself i think?

@MadeBaruna can i try to implement it? im still learning javascript, but i wanna learn about svelte

**Comment by MadeBaruna** [comment]
@fadhluu contribution welcome :)
