### ISSUE TITLE
Ошибки в Достижениях

### ISSUE THREAD

**Issue by Theatrical1** [MadeBaruna/paimon-moe#90]
1. Достижения в группах отображаются криво. Показываются только первые из какого-то общего списка. Из-за этого во всех группах одни и те же достижения, только если их "выполнить" в одной группе, в другой они остаются неотмеченными.
2. Меняющийся перевод достижений на русском языке в мобильной версии сайта. Если переместить Google Chrome в режим плавающего окна, переводы некоторых достижений меняется. Так, например, достиж. "...Ты всё слышал, не так ли?" превращается в "...Вы могли слышать Паймон всё время, не так ли?". В версии для ПК отображается все названия, как и в русской версии игры.
3. После включения сортировки достижений ("сначала невыполненные") в конец списка перемещаются совсем не те достижения, которые отмечались до этого. После отмены сортировки отмеченные достижения становятся прежними.

**Comment by MadeBaruna** [comment]
In English please, I can't read Russian :)
I can google translate it but might be better if you type it in English

Also what browser you use?
